### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by MrJoshFisher** [jpsingleton/Huxley#46]
Getting a 500 server error when doing a simple api call with my own key.

`https://huxley.apphb.com/all/stp/from/bxs/1?accessToken=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`

anyone else experiencing this ?

**Comment by menendezjaume** [comment]
It works for me.

https://huxley.apphb.com/all/stp/from/bxs/1?accessToken=x

Although the response I get is:

{
  "trainServices": null,
  "busServices": null,
  "ferryServices": null,
  "generatedAt": "2016-08-28T06:51:22.6429266+00:00",
  "locationName": "London St Pancras (Intl)",
  "crs": "STP",
  "filterLocationName": "Brussels Midi",
  "filtercrs": "BXS",
  "filterType": 1,
  "nrccMessages": null,
  "platformAvailable": true,
  "areServicesAvailable": true
}

This either because there are no services expected in the near future or because connections between train services need to be made manually. 
Is your token working with other API calls?

**Comment by jpsingleton** [comment]
This appear to be working fine, so if you are still having problems with your query results not matching the example then it is likely that your API key is incorrect or invalid.

You could try a different query such as https://huxley.apphb.com/all/lbg?expand=true&accessToken=DA1C7740-9DA0-11E4-80E6-A920340000B1.

If replacing the demo key with your key stops it working then the problem is with your key. Otherwise there probably just aren't any services when you are testing.
