### ISSUE TITLE
When using the departures api, 'sta'/'eta' are always null

### ISSUE THREAD

**Issue by geotre** [jpsingleton/Huxley#49]
Is this a problem with the upstream data?

**Comment by jpsingleton** [comment]
Yes, this is an upstream "feature" and is how the Darwin web service works.

On the `departures` API you will only get departure times. [For example:](https://huxley.apphb.com/departures/lbg/1?accessToken=DA1C7740-9DA0-11E4-80E6-A920340000B1)

``` javascript
"sta": null,
"eta": null,
"std": "15:57",
"etd": "On time",
```

On the `arrivals` API you will only get arrival times. [For example:](https://huxley.apphb.com/arrivals/lbg/1?accessToken=DA1C7740-9DA0-11E4-80E6-A920340000B1)

``` javascript
"sta": "15:59",
"eta": "On time",
"std": null,
"etd": null,
```

On the `all` API (arrivals & departures) you will get both times. [For example:](https://huxley.apphb.com/all/lbg/1?accessToken=DA1C7740-9DA0-11E4-80E6-A920340000B1)

``` javascript
"sta": "16:03",
"eta": "On time",
"std": "16:04",
"etd": "On time",
```

However, on the `staffdepartures` API you will also get all times, and they are `DateTime` objects rather than strings. [For example:](https://huxley.apphb.com/staffdepartures/lbg/1?accessToken=DA1C7740-9DA0-11E4-80E6-A920340000B1)

``` javascript
"sta": "2016-10-24T16:12:00",
"ata": "2016-10-24T16:09:00",
"std": "2016-10-24T16:13:00",
"etd": "2016-10-24T16:13:00",
```

Keep in mind that you won't always have all the times, depending on the service. For example, if the station is the origin then logically there will be no arrival time and likewise if it is the destination then there will be no departure time.
