### ISSUE TITLE
Example deployment to Azure

### ISSUE THREAD

**Issue by jpsingleton** [jpsingleton/Huxley#8]
Got a deployment in App Harbor but worth checking it works in Azure too. Do this from AppVeyor after tests.

This may enable things like push notifications using hubs and / or doing some ML on the train data.

**Comment by jpsingleton** [comment]
See if this can work as a cloud / mobile service.

**Comment by agentcare** [comment]
Work fine on Azure cloud service, really interested in the delay part, great work

**Comment by jpsingleton** [comment]
Cheers! Good to know. I built the delay part for [this project](https://unop.uk/dev/train-disruption-indicator-with-a-blinky-tape-rgb-led-strip-and-raspberry-pi/) but hopefully it will be useful to others.

I want to make Huxley as flexible as possible for deployments. As it's Web API based it doesn't have to run within IIS but can be run as a console app or as a service (with a little bit of work). I'll try to make it fully OWIN compatible at some point and when Core CLR is ready port it to Linux/BSD.

**Comment by jpsingleton** [comment]
https://huxley.azurewebsites.net/

**Comment by agentcare** [comment]
Excellent, I am concentrating on building a front end and a database at the moment but ultimately I also need a service running with a bit of business logic to push notification when there has been a significant delay or cancellations.  Blinky tape thing is brilliant by the way. I got a bizspark account running at the moment so that's why I am focusing on Azure
http://traindelayrefund.azurewebsites.net/
